### ISSUE TITLE
How long time does need when  process bash draw_fake.sh

### ISSUE THREAD

**Issue by Acmenwangtuo** [SBU-BMI/quip_cnn_segmentation#4]
As you see,I have only one iamge in read_tile, a few hours later,there is no result

**Comment by scotthoule** [comment]
Hi Acmenwangtuo,

1. Is there anything in the log or nohup.out?
2. You need to put a lot of images under read_tiles. And these images should be at least 1200 by 1200 pixels. The program checks statistics of generated fake patches and may reject outputing them. Some images under read_tiles will never generate satisfying fake patches.

Thx
