### ISSUE TITLE
Fail to download cancerType_polygon files from Box

### ISSUE THREAD

**Issue by WxpHB** [SBU-BMI/quip_cnn_segmentation#7]
Thx for your excellent work，but i can't download the segmentation result from the netaddress you provide, PS, i can download the WSI quickly.

**Comment by lehougoogle** [comment]
Hi WxpHB,

Can you provide details of how the downloading fails?
I tried downloading the data and it works on my side. I'm using google chrome incognito mode, and download the compressed files in https://stonybrookmedicine.app.box.com/v/cnn-nuclear-segmentations-2019/folder/87410320609 works for me.

Thx

**Comment by WxpHB** [comment]
Thx for your reminding！It works for me while the incognito mode is activated.

**Comment by WxpHB** [comment]
> 
> 
> Hi WxpHB,
> 
> Can you provide details of how the downloading fails?
> I tried downloading the data and it works on my side. I'm using google chrome incognito mode, and download the compressed files in https://stonybrookmedicine.app.box.com/v/cnn-nuclear-segmentations-2019/folder/87410320609 works for me.
> 
> Thx



> 
> 
> Hi WxpHB,
> 
> Can you provide details of how the downloading fails?
> I tried downloading the data and it works on my side. I'm using google chrome incognito mode, and download the compressed files in https://stonybrookmedicine.app.box.com/v/cnn-nuclear-segmentations-2019/folder/87410320609 works for me.
> 
> Thx

Thx for your reminding！It works for me while the incognito mode is activated.
