### ISSUE TITLE
*.SVS is't registered with it's mask.

### ISSUE THREAD

**Issue by WxpHB** [SBU-BMI/quip_cnn_segmentation#8]
Hi, maintainer:
    I slice [:20000,0:20000] from both *.svs and it's mask for a test, but they don't registered.
    The tested WSI is TCGA-4J-AA1J-01Z-00-DX1.8E768211-46FC-45A4-8689-6DDEA0198D43.svs
![捕获](https://user-images.githubusercontent.com/47773138/99475171-efc6b400-2988-11eb-847f-fa6ec58abd58.JPG)

**Comment by lehougoogle** [comment]
Hi,

Did you use for following file for extracting segmentation mask (see segmentation-of-nuclei/READMD.md)?
https://github.com/SBU-BMI/quip_cnn_segmentation/blob/master/segmentation-of-nuclei/extract_patch_segmentation_mask.py

If yes, is this the only image you tested?
If no, please try that script. The microns per-pixel (mpp) value in each whole slide image might not be exactly 0.25, which will make the scaling different.

Thx

**Comment by WxpHB** [comment]
Hi,
I used the script you provide to extract segmentation mask,and i tested several WSIs. The image and it's mask still can't be registered.  For example：

![图片](https://user-images.githubusercontent.com/47773138/99606633-1813e880-2a45-11eb-8e38-0a828d1b3854.png)
![图片](https://user-images.githubusercontent.com/47773138/99606671-282bc800-2a45-11eb-9056-389f744dcada.png)
![图片](https://user-images.githubusercontent.com/47773138/99606699-3843a780-2a45-11eb-9e63-9b38f7a439fe.png)
![图片](https://user-images.githubusercontent.com/47773138/99606709-4396d300-2a45-11eb-8610-7fd8482acf00.png)

for detail：
segmentation mask:
![test_10](https://user-images.githubusercontent.com/47773138/99606779-62956500-2a45-11eb-80ea-fa2701f6794f.png)

difference between WSI slice and it's mask：
![difference_4000](https://user-images.githubusercontent.com/47773138/99606817-73de7180-2a45-11eb-9c50-dee653e074f8.png)

**Comment by WxpHB** [comment]
and even in the different place of the same slice，there are displacement in different direction，for example：
left-down direction displacement
![direction_1](https://user-images.githubusercontent.com/47773138/99608357-ab9ae880-2a48-11eb-945a-02c8e96408f2.JPG)
right-down direction displacement
![direction_2](https://user-images.githubusercontent.com/47773138/99608449-e3099500-2a48-11eb-8154-4c9f4deeba78.png)

**Comment by lehougoogle** [comment]
Hi,

Sorry to see errors.
From the figure "difference between WSI slice and its mask", I see that on the top-left corner, the image and the mask sort of aligned. So this probably indicates scaling issue.

From your python code, I see that you extract image regions without scaling. Can you rerun the extract_patch_segmentation_mask.py by setting scale_to_40X to False?
https://github.com/SBU-BMI/quip_cnn_segmentation/blob/master/segmentation-of-nuclei/extract_patch_segmentation_mask.py#L30

For the last to patches you showed where the displacements are inconsistent, what were the <x, y> coordinates of these two patches? Maybe that would give me a hint of where the problem might be.

Thx

**Comment by scotthoule** [comment]
Hi WxpHB,

Have you tried setting scale_to_40X to False? If yes, does the mis-alignment problem still persist?

Thx

**Comment by alphaccw** [comment]
After setting the scale_to_40X to False, for my test image, the displacement problem is solved.

**Comment by alphaccw** [comment]
After setting the scale_to_40X to False, for my test image, the displacement problem is solved.

Thanks a lot.

**Comment by WxpHB** [comment]
> 
> 
> Hi,
> 
> Sorry to see errors.
> From the figure "difference between WSI slice and its mask", I see that on the top-left corner, the image and the mask sort of aligned. So this probably indicates scaling issue.
> 
> From your python code, I see that you extract image regions without scaling. Can you rerun the extract_patch_segmentation_mask.py by setting scale_to_40X to False?
> https://github.com/SBU-BMI/quip_cnn_segmentation/blob/master/segmentation-of-nuclei/extract_patch_segmentation_mask.py#L30
> 
> For the last two patches you showed where the displacements are inconsistent, what were the <x, y> coordinates of these two patches? Maybe that would give me a hint of where the problem might be.
> 
> Thx

Hi，

Please forgive a layman of WSI for asking that stupid question,problem solved,thank for your excellent work!

**Comment by scotthoule** [comment]
No worries at all. Please do not hesitate to leave a message should you have further questions.
